
package hk.neware.mvne.portal.soap.bss4mvno;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Bss4MvnoServiceImplService", targetNamespace = "http://bss4mvno.soap.portal.mvne.neware.hk/", wsdlLocation = "http://203.160.90.165:8080/services/bss4MvnoService?wsdl")
public class Bss4MvnoServiceImplService
    extends Service
{

    private final static URL BSS4MVNOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BSS4MVNOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BSS4MVNOSERVICEIMPLSERVICE_QNAME = new QName("http://bss4mvno.soap.portal.mvne.neware.hk/", "Bss4MvnoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://203.160.90.165:8080/services/bss4MvnoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSS4MVNOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BSS4MVNOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public Bss4MvnoServiceImplService() {
        super(__getWsdlLocation(), BSS4MVNOSERVICEIMPLSERVICE_QNAME);
    }

    public Bss4MvnoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSS4MVNOSERVICEIMPLSERVICE_QNAME, features);
    }

    public Bss4MvnoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BSS4MVNOSERVICEIMPLSERVICE_QNAME);
    }

    public Bss4MvnoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSS4MVNOSERVICEIMPLSERVICE_QNAME, features);
    }

    public Bss4MvnoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bss4MvnoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Bss4MvnoService
     */
    @WebEndpoint(name = "Bss4MvnoServiceImplPort")
    public Bss4MvnoService getBss4MvnoServiceImplPort() {
        return super.getPort(new QName("http://bss4mvno.soap.portal.mvne.neware.hk/", "Bss4MvnoServiceImplPort"), Bss4MvnoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Bss4MvnoService
     */
    @WebEndpoint(name = "Bss4MvnoServiceImplPort")
    public Bss4MvnoService getBss4MvnoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bss4mvno.soap.portal.mvne.neware.hk/", "Bss4MvnoServiceImplPort"), Bss4MvnoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSS4MVNOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BSS4MVNOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BSS4MVNOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
